### ISSUE TITLE
nginx fails to build

### ISSUE THREAD

**Issue by sogaiu** [andrewchambers/hpkgs#59] opened 2020-05-26 01:17 UTC
Trying to build nginx, here I get output that ends in:
```
checking for PCRE library ... not found
checking for PCRE library in /usr/local/ ... not found
checking for PCRE library in /usr/include/pcre/ ... not found
checking for PCRE library in /usr/pkg/ ... not found
checking for PCRE library in /opt/local/ ... not found

./configure: error: the HTTP rewrite module requires the PCRE library.
You can either disable the module by using --without-http_rewrite_module
option, or install the PCRE library into the system, or build the PCRE library
statically from the source with nginx by using --with-pcre=<path> option.

error: command(s) (@[./configure --prefix= :^ "/hpkg/5195830cc0dc6e8cbd74aecdb60f0b76715f3a8c-nginx"]) failed, exit code(s) @[1]
  in $* [/home/user/src/hermes/janet_modules/sh.janet] on line 220, column 5
  in <anonymous> [/home/user/src/hpkgs.sogaiu/community/nginx.hpkg] (tailcall) on line 44, column 6
  in do-build [src/pkgstore.janet] (tailcall) on line 575, column 23
error: builder failed
  in <anonymous> [src/pkgstore.janet] on line 588, column 17
  in run-builder [src/pkgstore.janet] on line 477, column 9
  in <anonymous> [src/pkgstore.janet] on line 458, column 21
  in build-pkg [src/pkgstore.janet] on line 449, column 17
  in <anonymous> [src/pkgstore.janet] on line 629, column 13
  in <anonymous> [src/pkgstore.janet] on line 433, column 3
  in <anonymous> [src/pkgstore.janet] on line 432, column 3
  in build [src/pkgstore.janet] on line 431, column 3
  in build [src/hermes-pkgstore-main.janet] on line 171, column 3
  in <anonymous> [src/hermes-pkgstore-main.janet] on line 288, column 19
  in main [src/hermes-pkgstore-main.janet] on line 285, column 3
```

**Comment by andrewchambers** [comment] 2020-05-26 01:31
Will check it out, we need a merging/package checklist haha.

**Comment by sogaiu** [comment] 2020-05-26 01:55
Perhaps so.

For nginx I guess there's an option to statically link pcre by including a directory to the source or something?

**Comment by andrewchambers** [comment] 2020-05-26 01:56
The problem is single user mode allows the build to look for libpcre inside /usr/include. The build will find them, and this alters the build.

**Comment by andrewchambers** [comment] 2020-05-26 02:00
The problem specifically is this test logic here: https://github.com/nginx/nginx-releases/blob/master/auto/lib/pcre/conf#L105

**Comment by sogaiu** [comment] 2020-05-26 10:01
It looks like nginx actually requires an older version of pcre.

I've renamed the existing pcre as pcre2, and have prepared updated pcre and nginx packages.

@roobie Hope this works ok for you.

**Comment by roobie** [comment] 2020-05-26 11:56
👍 No problem at all! I realize I have to learn more about the specifics before making more pull requests with new hpkgs. I guess a good start is to build them in multi user mode, because it would seem I could've caught this if built in a chroot, if I understand correctly.

Perhaps we/I should look into making a `CONTRIBUTING.md` that outlines the general process of adding hpkgs and what to think about before adding one?

**Comment by andrewchambers** [comment] 2020-05-26 13:37
@roobie sure, we discussed coming up with a checklist and package linter, though haven't done anything concrete yet.

**Comment by roobie** [comment] 2020-05-28 13:49
With the changes from @sogaiu the package build in chroot, for me, so should we close this issue?

**Comment by andrewchambers** [comment] 2020-05-28 13:50
Sure

**Closed as completed by andrewchambers** 2020-05-28 13:50 UTC
